/**
 * Whispers Coin wallet addresses.
 *
 * Format: WHISPERS-XXXX-XXXX-XXXX-XXXX
 *
 * The 16 payload characters are Crockford base32 — the alphabet drops I, L, O
 * and U so there is nothing to misread when someone types an address by hand.
 * Addresses are generated by the database (`public.generate_wallet_address`),
 * never on the client, and contain no part of the account they belong to.
 *
 * The helpers here mirror the SQL functions of the same names so the client can
 * validate a paste before spending a round trip. The database repeats every
 * check regardless — this is a UX shortcut, not the security boundary.
 */

/** Crockford base32, minus the characters that invite transcription errors. */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

const PAYLOAD_LENGTH = 16;
const PAYLOAD_PATTERN = new RegExp(`^[${ALPHABET}]{${PAYLOAD_LENGTH}}$`);

export const WALLET_PREFIX = "WHISPERS";
export const WALLET_ADDRESS_EXAMPLE = "WHISPERS-XXXX-XXXX-XXXX-XXXX";

/** Whispers does not charge to move coins between wallets. */
export const TRANSFER_FEE = 0;

function groupPayload(payload: string) {
  return `${WALLET_PREFIX}-${payload.slice(0, 4)}-${payload.slice(4, 8)}-${payload.slice(
    8,
    12
  )}-${payload.slice(12, 16)}`;
}

/**
 * Canonicalises anything a user might realistically paste: lowercase, missing
 * dashes, wrapping whitespace, a bare payload with the prefix trimmed off, or
 * the O/0 and I/1 substitutions the alphabet is chosen to absorb.
 *
 * Returns null when the input isn't a Whispers address at all.
 */
export function normalizeWalletAddress(input: string | null | undefined): string | null {
  if (!input) return null;

  const cleaned = input.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();

  // Tolerate a bare payload so copying just the code half still works.
  let payload = cleaned.startsWith(WALLET_PREFIX)
    ? cleaned.slice(WALLET_PREFIX.length)
    : cleaned;

  // Crockford aliases — applied only to the payload, never to the prefix
  // (which legitimately contains I and S).
  payload = payload.replace(/[IL]/g, "1").replace(/O/g, "0");

  if (!PAYLOAD_PATTERN.test(payload)) return null;

  return groupPayload(payload);
}

export function isValidWalletAddress(input: string | null | undefined): boolean {
  return normalizeWalletAddress(input) !== null;
}

/**
 * Shortened form for receipts and history rows: `WHISPERS-A1B2…X9Y8`.
 *
 * Addresses aren't personal information, but a receipt is the kind of thing
 * people screenshot, so history and receipts show the short form and only the
 * wallet's owner sees their own address in full.
 */
export function maskWalletAddress(address: string | null | undefined): string {
  if (!address) return "";
  if (address.length <= 18) return address;
  return `${address.slice(0, 13)}…${address.slice(-4)}`;
}

/**
 * Splits a canonical address into its display groups so the UI can lay it out
 * without re-parsing. Returns a single group for anything non-canonical.
 */
export function walletAddressGroups(address: string | null | undefined): string[] {
  if (!address) return [];
  const parts = address.split("-");
  return parts.length === 5 ? parts.slice(1) : [address];
}

/* -------------------------------------------------------------------------- */
/* Transfers                                                                  */
/* -------------------------------------------------------------------------- */

export type TransferStatus = "completed" | "failed";

/** The receipt shape returned by `transfer_whisper_coins` / `get_transfer_receipt`. */
export type TransferReceipt = {
  status: TransferStatus;
  reference: string;
  amount: number;
  fee: number;
  /** Already masked by the database. */
  sender_address: string | null;
  /** Already masked by the database. Null when the address never resolved. */
  recipient_address: string | null;
  created_at: string;
  balance?: number;
  failure_reason: string | null;
  /** Present when an idempotent retry returned the original receipt. */
  replayed?: boolean;
  direction?: "in" | "out";
};

export type AmountValidation = { valid: boolean; error: string | null };

/**
 * Client-side amount check. Coins are whole numbers everywhere in the app —
 * `coins.balance` is an integer column — so decimals are rejected rather than
 * rounded, which would silently move a different amount than the one typed.
 */
export function validateTransferAmount(raw: string, balance: number): AmountValidation {
  const trimmed = raw.trim();
  if (!trimmed) return { valid: false, error: null };

  if (!/^\d+$/.test(trimmed)) {
    return { valid: false, error: "Whole coins only — no decimals." };
  }

  const amount = Number(trimmed);
  if (!Number.isSafeInteger(amount) || amount <= 0) {
    return { valid: false, error: "Enter an amount greater than zero." };
  }
  if (amount > balance) {
    return {
      valid: false,
      error: `You only have ${balance.toLocaleString()} coin${balance === 1 ? "" : "s"}.`,
    };
  }

  return { valid: true, error: null };
}

/** Formats a receipt timestamp consistently across the receipt and history. */
export function formatTransferTimestamp(value: string | null | undefined): string {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}
