/**
 * Whispers Coin wallet addresses.
 *
 * Format: WHISPERS-XXXX-XXXX-XXXX-XXXX
 *
 * The 16 payload characters are Crockford base32 — the alphabet drops I, L, O
 * and U so there is nothing to misread when someone types an address by hand.
 * Addresses are generated by the database (`public.generate_wallet_address`),
 * never on the client, and contain no part of the account they belong to.
 *
 * The helpers here mirror the SQL functions of the same names so the client can
 * validate a paste before spending a round trip. The database repeats every
 * check regardless — this is a UX shortcut, not the security boundary.
 */

/** Crockford base32, minus the characters that invite transcription errors. */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

const PAYLOAD_LENGTH = 16;
const PAYLOAD_PATTERN = new RegExp(`^[${ALPHABET}]{${PAYLOAD_LENGTH}}$`);

export const WALLET_PREFIX = "WHISPERS";
export const WALLET_ADDRESS_EXAMPLE = "WHISPERS-XXXX-XXXX-XXXX-XXXX";

/** Whispers does not charge to move coins between wallets. */
export const TRANSFER_FEE = 0;

function groupPayload(payload: string) {
  return `${WALLET_PREFIX}-${payload.slice(0, 4)}-${payload.slice(4, 8)}-${payload.slice(
    8,
    12
  )}-${payload.slice(12, 16)}`;
}

/**
 * Canonicalises anything a user might realistically paste: lowercase, missing
 * dashes, wrapping whitespace, a bare payload with the prefix trimmed off, or
 * the O/0 and I/1 substitutions the alphabet is chosen to absorb.
 *
 * Returns null when the input isn't a Whispers address at all.
 */
export function normalizeWalletAddress(input: string | null | undefined): string | null {
  if (!input) return null;

  const cleaned = input.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();

  // Tolerate a bare payload so copying just the code half still works.
  let payload = cleaned.startsWith(WALLET_PREFIX)
    ? cleaned.slice(WALLET_PREFIX.length)
    : cleaned;

  // Crockford aliases — applied only to the payload, never to the prefix
  // (which legitimately contains I and S).
  payload = payload.replace(/[IL]/g, "1").replace(/O/g, "0");

  if (!PAYLOAD_PATTERN.test(payload)) return null;

  return groupPayload(payload);
}

export function isValidWalletAddress(input: string | null | undefined): boolean {
  return normalizeWalletAddress(input) !== null;
}

/**
 * Shortened form for receipts and history rows: `WHISPERS-A1B2…X9Y8`.
 *
 * Addresses aren't personal information, but a receipt is the kind of thing
 * people screenshot, so history and receipts show the short form and only the
 * wallet's owner sees their own address in full.
 */
export function maskWalletAddress(address: string | null | undefined): string {
  if (!address) return "";
  if (address.length <= 18) return address;
  return `${address.slice(0, 13)}…${address.slice(-4)}`;
}

/**
 * Splits a canonical address into its display groups so the UI can lay it out
 * without re-parsing. Returns a single group for anything non-canonical.
 */
export function walletAddressGroups(address: string | null | undefined): string[] {
  if (!address) return [];
  const parts = address.split("-");
  return parts.length === 5 ? parts.slice(1) : [address];
}

/* -------------------------------------------------------------------------- */
/* Transfers                                                                  */
/* -------------------------------------------------------------------------- */

export type TransferStatus = "completed" | "failed";

/** The receipt shape returned by `transfer_whisper_coins` / `get_transfer_receipt`. */
export type TransferReceipt = {
  status: TransferStatus;
  reference: string;
  amount: number;
  fee: number;
  /** Already masked by the database. */
  sender_address: string | null;
  /** Already masked by the database. Null when the address never resolved. */
  recipient_address: string | null;
  created_at: string;
  balance?: number;
  failure_reason: string | null;
  /** Present when an idempotent retry returned the original receipt. */
  replayed?: boolean;
  direction?: "in" | "out";
};

export type AmountValidation = { valid: boolean; error: string | null };

/* -------------------------------------------------------------------------- */
/* The ledger, and receipts for every row in it                               */
/* -------------------------------------------------------------------------- */

/**
 * One row of `public.coin_transactions`.
 *
 * Lives here rather than beside the history component because two things now
 * need it — the list that renders rows and the function below that turns a row
 * into a receipt — and a shared type belongs above both of them, not inside one.
 */
export type CoinTransaction = {
  id: string;
  amount: number;
  description: string;
  transaction_type: string;
  created_at: string;
  /** Transfers only. Ledger entries from spends, rewards and grants have none. */
  reference?: string | null;
};

/**
 * A receipt for any wallet movement, not just a transfer.
 *
 * WHY THIS IS A SUPERSET RATHER THAN A SECOND TYPE
 *
 * Only transfers have a counterparty, a fee and a server-issued reference, and
 * only transfers can fail — so only transfers can be described by
 * `get_transfer_receipt`. Every other row (a purchase, a spend, a refund, a
 * streak reward, an admin grant) is a settled fact with no second party, and the
 * ledger row itself already contains everything a receipt for it needs.
 *
 * Two receipt *types* would mean two receipt *modals*, and the second one would
 * drift from the first the first time either was touched. Instead the transfer
 * shape is widened with three optional fields that describe what to render, and
 * `receiptFromTransaction` fills them in for the rows the RPC cannot describe.
 * One component, one visual language, no duplicated markup.
 */
export type WalletReceipt = TransferReceipt & {
  /** The "Transaction type" row. Defaults to "Coin Transfer" when absent. */
  type_label?: string;
  /** The ledger row's own wording — "Unlock Chat", "7-day streak reward". */
  detail?: string | null;
  /** False for ledger rows: they have no fee, so the row is hidden entirely. */
  has_fee?: boolean;
};

/**
 * Human wording for each `transaction_type` the database writes.
 *
 * Kept as a map rather than a switch so an unrecognised type is a *missing
 * label*, not a crash: `receiptFromTransaction` falls back to a generic phrase.
 * That matters because the type check on `coin_transactions` is rebuilt from
 * whatever values already exist in the live table (see
 * `202608110001_coin_wallet_transfers.sql`), so a type can legitimately be
 * present in production that this file has never heard of.
 */
export const TRANSACTION_TYPE_LABELS: Record<string, string> = {
  purchase: "Coin Purchase",
  spend: "Coin Spend",
  refund: "Refund",
  reward: "Streak Reward",
  grant: "Coin Grant",
  transfer_in: "Coin Transfer",
  transfer_out: "Coin Transfer",
};

export function transactionTypeLabel(type: string): string {
  return (
    TRANSACTION_TYPE_LABELS[type] ??
    /* "some_new_type" → "Some New Type". Better than showing the raw enum, and
       better than "Transaction" because it keeps whatever meaning the value has. */
    type
      .split("_")
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ")
  );
}

/**
 * A receipt built entirely from a ledger row.
 *
 * Used for every transaction that is not a transfer. Nothing is fetched and
 * nothing is invented:
 *
 *   - `status` is always "completed". A row only exists in `coin_transactions`
 *     because the balance actually moved — the functions that write it do so in
 *     the same transaction as the `coins` update, so there is no such thing as a
 *     pending or failed ledger row to misreport.
 *   - `reference` is the row's own id. Ledger entries get no server-issued
 *     reference, and support cannot act on a receipt with nothing to quote, so
 *     the primary key is the honest answer rather than a fabricated code.
 *   - `sender_address` / `recipient_address` stay null so the modal omits both
 *     rows: there is no counterparty to name, and inventing "Whisper" as one
 *     would imply a wallet that does not exist.
 *   - `amount` keeps the ledger's sign, because the modal derives its direction
 *     arrow from it — a spend is stored negative and must read as outgoing.
 */
export function receiptFromTransaction(tx: CoinTransaction): WalletReceipt {
  return {
    status: "completed",
    reference: tx.reference || tx.id,
    amount: tx.amount,
    fee: 0,
    has_fee: false,
    sender_address: null,
    recipient_address: null,
    created_at: tx.created_at,
    failure_reason: null,
    direction: tx.amount >= 0 ? "in" : "out",
    type_label: transactionTypeLabel(tx.transaction_type),
    /* Suppressed when it would just repeat the type label — "Refund / Refund"
       is noise, and a receipt earns trust by having nothing redundant on it. */
    detail:
      tx.description && tx.description !== transactionTypeLabel(tx.transaction_type)
        ? tx.description
        : null,
  };
}

/** True for the rows `get_transfer_receipt` can describe. */
export function isTransferTransaction(tx: CoinTransaction): boolean {
  return (
    (tx.transaction_type === "transfer_in" || tx.transaction_type === "transfer_out") &&
    Boolean(tx.reference)
  );
}

/**
 * Client-side amount check. Coins are whole numbers everywhere in the app —
 * `coins.balance` is an integer column — so decimals are rejected rather than
 * rounded, which would silently move a different amount than the one typed.
 */
export function validateTransferAmount(raw: string, balance: number): AmountValidation {
  const trimmed = raw.trim();
  if (!trimmed) return { valid: false, error: null };

  if (!/^\d+$/.test(trimmed)) {
    return { valid: false, error: "Whole coins only — no decimals." };
  }

  const amount = Number(trimmed);
  if (!Number.isSafeInteger(amount) || amount <= 0) {
    return { valid: false, error: "Enter an amount greater than zero." };
  }
  if (amount > balance) {
    return {
      valid: false,
      error: `You only have ${balance.toLocaleString()} coin${balance === 1 ? "" : "s"}.`,
    };
  }

  return { valid: true, error: null };
}

/** Formats a receipt timestamp consistently across the receipt and history. */
export function formatTransferTimestamp(value: string | null | undefined): string {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toLocaleString(undefined, {
    dateStyle: "medium",
    timeStyle: "short",
  });
}
